// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgaDUIpJ4ICvo3R3QBf2_nBlP1p0joaJM',
    appId: '1:371787124672:web:e641823bb12e566f210225',
    messagingSenderId: '371787124672',
    projectId: 'ticketflow-1d36f',
    authDomain: 'ticketflow-1d36f.firebaseapp.com',
    storageBucket: 'ticketflow-1d36f.firebasestorage.app',
    measurementId: 'G-ZYSTJR51JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9rpz3xKrv-QCSo1RmfWjtvqgyPylLF6Q',
    appId: '1:371787124672:android:23324fa27aad9093210225',
    messagingSenderId: '371787124672',
    projectId: 'ticketflow-1d36f',
    storageBucket: 'ticketflow-1d36f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB_VyY5BROdE0xUeI-kXyXOA2QAQpr4CA',
    appId: '1:371787124672:ios:0fc0408ef756131e210225',
    messagingSenderId: '371787124672',
    projectId: 'ticketflow-1d36f',
    storageBucket: 'ticketflow-1d36f.firebasestorage.app',
    iosBundleId: 'com.example.ticketflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB_VyY5BROdE0xUeI-kXyXOA2QAQpr4CA',
    appId: '1:371787124672:ios:0fc0408ef756131e210225',
    messagingSenderId: '371787124672',
    projectId: 'ticketflow-1d36f',
    storageBucket: 'ticketflow-1d36f.firebasestorage.app',
    iosBundleId: 'com.example.ticketflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgaDUIpJ4ICvo3R3QBf2_nBlP1p0joaJM',
    appId: '1:371787124672:web:6081552d8fdf34a9210225',
    messagingSenderId: '371787124672',
    projectId: 'ticketflow-1d36f',
    authDomain: 'ticketflow-1d36f.firebaseapp.com',
    storageBucket: 'ticketflow-1d36f.firebasestorage.app',
    measurementId: 'G-TN0DTD4TZ7',
  );
}
